# Generated by Django 5.2.1 on 2025-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_judgelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_reset_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reset_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
