# Generated by Django 5.2.1 on 2026-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_last_reset_attempt_and_more'),
        ('competitions', '0008_alter_boulder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionrole',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='competitionrole',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn')], max_length=3, null=True),
        ),
        migrations.AddConstraint(
            model_name='competitionrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('user', 'competition', 'role'), name='unique_active_competition_role'),
        ),
    ]
