# Generated by Django 5.2.1 on 2026-05-30 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('simple_name', models.CharField(blank=True, max_length=100, null=True)),
                ('simple_age', models.IntegerField(blank=True, null=True)),
                ('simple_gender', models.CharField(blank=True, choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn'), ('OTHER', 'Annað')], max_length=6, null=True)),
                ('is_simple_athlete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('competition_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitioncategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('competition', 'climber', 'competition_category'), name='unique_active_registration')],
            },
        ),
    ]
