# Generated by Django 5.2.1 on 2026-05-27 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('competitions', '0008_alter_boulder_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='climber',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='climber',
            name='simple_gender',
            field=models.CharField(blank=True, choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='competitionregistration',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='competitionregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('competition', 'climber', 'competition_category'), name='unique_active_registration'),
        ),
    ]
