# Generated by Django 5.2.1 on 2026-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_competitionregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climber',
            name='simple_gender',
            field=models.CharField(blank=True, choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn'), ('OTHER', 'ANNAÐ')], max_length=6, null=True),
        ),
    ]
