# Generated by Django 5.2.1 on 2026-05-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_climber_simple_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climber',
            name='simple_gender',
            field=models.CharField(blank=True, choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn'), ('OTHER', 'Annað')], max_length=6, null=True),
        ),
    ]
