name: klifurmot
services:
  # Backend API service
  - name: web
    source_dir: /
    github:
      repo: solonthorberg/klifurmot
      branch: main
    build_command: python manage.py collectstatic --noinput
    run_command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8080 --workers 2 klifurmot.wsgi:application"
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: FRONTEND_BASE_URL
        value: https://klifurmot.ondigitalocean.app
      - key: ALLOWED_HOSTS
        value: klifurmot-web.ondigitalocean.app,klifurmot.ondigitalocean.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://klifurmot.ondigitalocean.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://klifurmot-web.ondigitalocean.app,https://klifurmot.ondigitalocean.app

  # React frontend
  - name: frontend
    source_dir: /klifurmot-frontend
    github:
      repo: solonthorberg/klifurmot
      branch: main
    build_command: npm ci && npm run build
    run_command: npx serve -s dist -p 8080 --single
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: VITE_API_URL
        value: https://klifurmot-web.ondigitalocean.app/api
