# Generated by Django 5.2.1 on 2025-10-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'ordering': ['min_age']},
        ),
        migrations.RemoveField(
            model_name='categorygroup',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='competitionround',
            name='is_default',
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
