# Generated by Django 5.2.1 on 2026-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='discipline',
            field=models.CharField(choices=[('boulder', 'Boulder'), ('lead', 'Lead')], default='boulder', max_length=10),
        ),
    ]
