# Generated by Django 5.2.1 on 2026-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_categorygroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boulders/'),
        ),
    ]
