# Generated by Django 5.2.1 on 2026-09-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_self_registration',
            field=models.BooleanField(default=False),
        ),
    ]
