# Generated by Django 5.2.1 on 2026-10-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_allow_self_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='startlist_visible',
            field=models.BooleanField(default=False),
        ),
    ]
