# Generated by Django 5.2.1 on 2026-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_boulder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
