# Generated by Django 5.2.1 on 2026-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_categorygroup_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='section_style',
            field=models.CharField(default='general', max_length=50, null=True),
        ),
    ]
