# Generated by Django 5.2.1 on 2026-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_boulder_section_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='section_style',
            field=models.CharField(blank=True, default='general', max_length=50, null=True),
        ),
    ]
