# Generated by Django 5.2.1 on 2026-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_boulder_section_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionround',
            name='climbers_advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
