# Generated by Django 5.2.1 on 2026-05-27 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_competitionround_climbers_advance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boulder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionround',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='gender',
            field=models.CharField(choices=[('KK', 'Karlkyn'), ('KVK', 'Kvenkyn')], max_length=3),
        ),
        migrations.AlterField(
            model_name='competitionround',
            name='climbers_advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitionround',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='boulder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('round', 'boulder_number'), name='unique_active_boulder'),
        ),
    ]
