# Generated by Django 5.2.1 on 2026-05-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_competitioncategory_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncategory',
            name='gender',
            field=models.CharField(choices=[('KK', 'KK'), ('KVK', 'KVK')], max_length=6),
        ),
    ]
