# Generated by Django 5.2.1 on 2026-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_competitioncategory_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionround',
            name='climbers_advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
