# Generated by Django 5.2.1 on 2026-05-30 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('completed', models.BooleanField(default=False)),
                ('attempts_zone', models.IntegerField(blank=True, null=True)),
                ('zone_reached', models.BooleanField(blank=True, null=True)),
                ('attempts_top', models.IntegerField(blank=True, null=True)),
                ('top_reached', models.BooleanField(blank=True, null=True)),
                ('hold_reached', models.IntegerField(blank=True, null=True)),
                ('plus_modifier', models.BooleanField(blank=True, null=True)),
                ('time_seconds', models.IntegerField(blank=True, null=True)),
                ('fall_position', models.IntegerField(blank=True, null=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.route')),
            ],
            options={
                'ordering': ['route__round', 'climber'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('climber', 'route'), name='unique_active_climb')],
            },
        ),
        migrations.CreateModel(
            name='ClimberRoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tops', models.IntegerField(blank=True, null=True)),
                ('zones', models.IntegerField(blank=True, null=True)),
                ('attempts_tops', models.IntegerField(blank=True, null=True)),
                ('attempts_zones', models.IntegerField(blank=True, null=True)),
                ('best_hold_reached', models.IntegerField(blank=True, null=True)),
                ('best_time_seconds', models.IntegerField(blank=True, null=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionround')),
            ],
            options={
                'ordering': ['-total_score'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('round', 'climber'), name='unique_active_round_score')],
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('start_order', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionround')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('round', 'climber'), name='unique_active_round_result')],
            },
        ),
    ]
