# Generated by Django 5.2.1 on 2025-09-16 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_zone', models.IntegerField(default=0)),
                ('zone_reached', models.BooleanField(default=False)),
                ('attempts_top', models.IntegerField(default=0)),
                ('top_reached', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.boulder')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['boulder__round', 'climber'],
                'unique_together': {('climber', 'boulder')},
            },
        ),
        migrations.CreateModel(
            name='ClimberRoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tops', models.IntegerField()),
                ('zones', models.IntegerField()),
                ('attempts_tops', models.IntegerField()),
                ('attempts_zones', models.IntegerField()),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionround')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('round', 'climber')},
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('start_order', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionround')),
            ],
            options={
                'unique_together': {('round', 'climber')},
            },
        ),
    ]
