# Generated by Django 5.2.1 on 2025-10-13 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('competitions', '0002_alter_categorygroup_options_and_more'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='climberroundscore',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='climberroundscore',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='climberroundscore',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SelfScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_reached', models.BooleanField(default=False)),
                ('zone_reached', models.BooleanField(default=False)),
                ('attempts_top', models.IntegerField(default=0)),
                ('attempts_zone', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('boulder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.boulder')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.climber')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_scores_created', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionround')),
            ],
            options={
                'ordering': ['boulder__boulder_number'],
                'unique_together': {('climber', 'boulder')},
            },
        ),
    ]
