# Generated by Django 5.2.1 on 2026-05-27 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_competitionregistration_unique_together_and_more'),
        ('competitions', '0008_alter_boulder_unique_together_and_more'),
        ('scoring', '0002_climberroundscore_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='climb',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='climberroundscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roundresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='selfscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='climberroundscore',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='climberroundscore',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfscore',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='selfscore',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='climb',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='climberroundscore',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='roundresult',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='selfscore',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selfscore',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='climb',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('climber', 'boulder'), name='unique_active_climb'),
        ),
        migrations.AddConstraint(
            model_name='climberroundscore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('round', 'climber'), name='unique_active_round_score'),
        ),
        migrations.AddConstraint(
            model_name='roundresult',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('round', 'climber'), name='unique_active_round_result'),
        ),
        migrations.AddConstraint(
            model_name='selfscore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('climber', 'boulder'), name='unique_active_self_score'),
        ),
        migrations.RemoveField(
            model_name='selfscore',
            name='last_updated_at',
        ),
    ]
